version: '3'

services:
  php-fpm:
    build:
      context: './'
      dockerfile: './docker/php-fpm/Dockerfile'
    volumes:
      - ./:/var/www/html/:cached

  nginx:
    build:
      context: './'
      dockerfile: './docker/nginx/Dockerfile'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./:/var/www/html/:cached
