version: '3'

services:
  php-fpm:
    image: sanderlissenburg/mathematics-php-fpm-dev
    volumes:
      - ./:/var/www/html/:cached
    networks:
      - mathematics
    labels:
      - "traefik.enable=false"

  nginx:
    image: sanderlissenburg/mathematics-nginx-dev
    volumes:
      - ./public:/var/www/html/public:cached
    networks:
      - mathematics
      - lissenburg-cluster
    labels:
      - "traefik.frontend.rule=Host:mathematics.lissenburg.local"

networks:
    lissenburg-cluster:
        external:
            name: lissenburg-cluster
    mathematics:
        driver: bridge
