version: '3'

services:
  php-fpm:
    image: sanderlissenburg/mathematics-php-fpm
    networks:
      - mathematics
    labels:
      - "traefik.enable=false"

  nginx:
    image: sanderlissenburg/mathematics-nginx
    networks:
      - mathematics
      - lissenburg-cluster
    labels:
      - "traefik.frontend.rule=Host:mathematics.lissenburg.nl"

networks:
    lissenburg-cluster:
        external:
            name: lissenburg-cluster
    mathematics:
        driver: bridge
